# Generated by Django 4.2.13 on 2024-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_birthday_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
