# Generated by Django 4.2.13 on 2024-07-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='phone',
            new_name='contact_no',
        ),
    ]
